/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#include "node/gen-cpp2/Node.h"
#include "node/gen-cpp2/Node.tcc"

namespace node { namespace cpp2 {
}} // node::cpp2
namespace apache { namespace thrift {

}} // apache::thrift
