/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#include "node/gen-cpp2/node_constants.h"

#include <folly/Indestructible.h>

namespace node { namespace cpp2 {

constexpr int8_t const node_constants::ERR_OK_;

constexpr int8_t const node_constants::ERR_SERVER_ERROR_;

}} // node::cpp2
