/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#pragma once

#include <thrift/lib/cpp2/protocol/Protocol.h>

#include "node_types.h"

namespace node { namespace cpp2 {

struct node_constants {

  static constexpr int8_t const ERR_OK_ = static_cast<int8_t>(0);

  static constexpr int8_t ERR_OK() {
    return ERR_OK_;
  }

  static constexpr int8_t const ERR_SERVER_ERROR_ = static_cast<int8_t>(13);

  static constexpr int8_t ERR_SERVER_ERROR() {
    return ERR_SERVER_ERROR_;
  }

};

}} // node::cpp2
